 1 file changed, 1 insertion(+)
PS C:\Users\adela\Documents\proyecto-celu> git push
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 8 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 324 bytes | 324.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0), pack-reused 0 (from 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/Pabloo626/proyecto-celu.git
   4ec3256..2dc71c9  main -> main
PS C:\Users\adela\Documents\proyecto-celu> 